### ISSUE TITLE
When a player is kicked from Velocity, the native MOTD is shown to him.

### ISSUE THREAD

**Issue by Pantera07** [Elytrium/FastMOTD#13]
When a player is kicked from Velocity, the native MOTD is shown to him.

How to reproduce:
Kick a player from Velocity or shut down Velocity.

**Comment by SkyWatcher2019** [comment]
Same, also happens when a player is kicked for timeout/internal error/etc.

**Comment by Pantera07** [comment]
Related?
https://github.com/PaperMC/Velocity/issues/769

**Comment by hevav** [comment]
I think you're right, these issues are related to our issue. Thanks

**Comment by hevav** [comment]
I don't know if it works, github closed the issue for me =)

**Comment by Pantera07** [comment]
This issue has been resolved.  It works fine.
