### ISSUE TITLE
Error with old pingers

### ISSUE THREAD

**Issue by steelswing** [Elytrium/FastMOTD#22]
Pinger https://mcsrvstat.us/: **Could not get the server status**

Console: 
x.x.x.x:xxxx is pinging the server with version Unknown (0x00) 

Apparently FastMOTD does not respond to protocol 0x00, although the vanilla server is responding, please fix it.

**Comment by belphegorspn** [comment]
Bumping this. Can't verify in planet minecraft if FastMOTD is installed.

**Comment by Narrow-band** [comment]
Also bumping as I have this same issue. This also affects player counters on my website and tebex.

**Comment by steelswing** [comment]
class net.elytrium.fastmotd.injection.HandshakeSessionHandlerHook

Fix this problem: 
![image](https://github.com/Elytrium/FastMOTD/assets/53971838/42f43c41-1f51-41d5-8fe9-0bcf49b3e35e)


```java
        if (handshake.getProtocolVersion() == null || handshake.getProtocolVersion() == ProtocolVersion.UNKNOWN) {
            handshake.setProtocolVersion(ProtocolVersion.MINIMUM_VERSION);
            if (Settings.IMP.MAIN.LOG_PINGS) {
                this.plugin.getLogger().info("Replace protocol to " + ProtocolVersion.MINIMUM_VERSION);
            }
        }
```

**Comment by Panic-exe** [comment]
Have this problem solved? Ia have this problem in the MOTD, i have 3 different IPS to connect in my server, but if i click in "Refresh", only one IP loads the MOTD, the another 2 IPS only get error... How to fix?
