### ISSUE TITLE
Can't get good support in China.

### ISSUE THREAD

**Issue by FuDujilm** [Elytrium/FastMOTD#33]
Hello, Elytrium and programmers. I am using your plugin but am unable to receive proper support. When I attempt to update your plugin, it fails to check for updates. I understand this may be related to the GFW issue. To use fastmotd, I must connect through VPN-TUN. However, when I try to run the plugin, the terminal reports an update error. While your other plugins function correctly, fastmotd does not display messages properly on the Minecraft server page.

Here is my error log: log when I am not using the VPN.

This is my motd show.

![image](https://github.com/Elytrium/FastMOTD/assets/72288165/8230ef60-4083-43f4-832f-8bbb4204af3c)
It seemed try to connect my server (spent a long time. sometimes it shows a connection error message) but the lastly it return me a velocity default motd message.

![image](https://github.com/Elytrium/FastMOTD/assets/72288165/f7a90099-5921-4c96-b897-5a469b864836)

This is my true motd text.
![image](https://github.com/Elytrium/FastMOTD/assets/72288165/3bc1dbcf-1118-4f09-963f-917510a3b54d)

Thank you for reading my issue. I hope you have a good time!
Lastly, I sincerely hope this problem can be resolved.
Looking forward to your prompt reply!
Love from China❤

**Comment by FuDujilm** [comment]
When the problem happened, I can connect my sever still.

**Comment by UserNugget** [comment]
Fixed by https://github.com/Elytrium/FastMOTD/commit/c5e2accdd03fdbce247827059ad9b19c2221a32e
