### ISSUE TITLE
Couldn't start the Velocity with the FastMOTD installed

### ISSUE THREAD

**Issue by yanxuplay** [Elytrium/FastMOTD#34]
I installed FastMOTD-1.0.2-jdk17.jar but it can't run as I expected,Velocity says "Can't create plugin fastmotd".
Thanks for solving my problems.

Log: [2024-06-09-7.log.gz](https://github.com/user-attachments/files/15749032/2024-06-09-7.log.gz)

**Comment by SkyWatcher2019** [comment]
![image](https://github.com/Elytrium/FastMOTD/assets/62600934/a6d682e3-d132-4bb4-8681-47449391826b)

As always, [outdated plugin](https://github.com/Elytrium/FastMOTD/releases/tag/1.0.6)
